// --- START OF FILE js/client.js ---
import { DB } from './database.js';
import { RfiModule } from './site_modules/rfi_module.js';
import { MomModule } from './site_modules/mom_module.js';
import { MaterialsModule } from './site_modules/materials_module.js';
import { BulletinModule } from './site_modules/bulletin_module.js';
// Reporting usually not generated by client, but they might view reports.

const AppState = {
    currentJobNo: null,
    currentUserRole: 'client',
    calendarDate: new Date()
};

const AppContext = {
    getState: () => AppState,
    onUpdate: (moduleName) => {
        // Client mostly reads, but if they add a comment (future), refresh here.
    }
};

document.addEventListener('DOMContentLoaded', async () => {
    await DB.init();
    
    // Modules Init (Mostly for viewing, so we might pass null for 'add' buttons if client can't add)
    RfiModule.init({}, AppContext); 
    MomModule.init({}, AppContext);

    document.getElementById('project-list-body').addEventListener('click', handleProjectSelect);
    renderProjectList();
});

async function handleProjectSelect(e) {
    const row = e.target.closest('tr');
    if (!row) return;
    
    AppState.currentJobNo = row.dataset.jobNo;
    
    // Render Modules in Read-Only contexts (if logic supports it, otherwise standard render)
    RfiModule.render(AppState.currentJobNo, document.getElementById('rfi-log-list'), AppState.currentUserRole);
    MomModule.renderList(AppState.currentJobNo, document.getElementById('mom-list'));
    // Render Task Followup for Client
    MomModule.renderTaskFollowUp(AppState.currentJobNo, document.getElementById('mom-list'));
    
    // Show Details View
    // ...
}

async function renderProjectList() {
    const tbody = document.getElementById('project-list-body');
    const allProjects = await DB.getAllProjects();
    // Filter logic: Only show projects belonging to this client (mock logic or DB filter)
    const clientProjects = allProjects; // .filter(p => p.clientName === 'Logged In Client Name')
    
    tbody.innerHTML = '';
    clientProjects.forEach(p => {
        const row = tbody.insertRow();
        row.dataset.jobNo = p.jobNo;
        row.innerHTML = `<td>${p.jobNo}</td><td>${p.projectDescription}</td><td>${p.status || 'Active'}</td>`;
    });
}