const DB = (() => {
    let db;
    const DB_NAME = 'UrbanAxisSiteDB';
    const DB_VERSION = 1;

    const STORES = {
        PROJECTS: 'projects',       // Master project data from main office
        SITE_DATA: 'siteData',      // Data generated by site engineer (status, BOQ progress, MoM)
        FILES: 'files'              // Blobs for photos, documents uploaded by site engineer
    };

    function init() {
        return new Promise((resolve, reject) => {
            console.log(`Opening database ${DB_NAME} version ${DB_VERSION}...`);
            const request = indexedDB.open(DB_NAME, DB_VERSION);

            request.onerror = (event) => {
                console.error("Database error:", event.target.error);
                reject(event.target.error);
            };

            request.onupgradeneeded = (event) => {
                console.log("Database upgrade needed.");
                db = event.target.result;

                if (!db.objectStoreNames.contains(STORES.PROJECTS)) {
                    db.createObjectStore(STORES.PROJECTS, { keyPath: 'jobNo' });
                    console.log(`Object store '${STORES.PROJECTS}' created.`);
                }
                if (!db.objectStoreNames.contains(STORES.SITE_DATA)) {
                    db.createObjectStore(STORES.SITE_DATA, { keyPath: 'jobNo' });
                    console.log(`Object store '${STORES.SITE_DATA}' created.`);
                }
                if (!db.objectStoreNames.contains(STORES.FILES)) {
                    const fileStore = db.createObjectStore(STORES.FILES, { keyPath: 'id', autoIncrement: true });
                    fileStore.createIndex('jobNo_type', ['jobNo', 'type'], { unique: false });
                    console.log(`Object store '${STORES.FILES}' created.`);
                }
            };

            request.onsuccess = (event) => {
                db = event.target.result;
                console.log("Database initialized successfully.");
                resolve();
            };
        });
    }

    function makeRequest(storeName, mode, action, data, key) {
        return new Promise((resolve, reject) => {
            if (!db) return reject("Database not initialized.");
            
            try {
                const transaction = db.transaction(storeName, mode);
                transaction.onerror = (event) => reject(`Transaction error on ${storeName}: ${event.target.error.name}`);
                
                const store = transaction.objectStore(storeName);
                const request = action === 'delete' ? store.delete(key) : store[action](data);
                
                request.onerror = (event) => reject(`Request error on ${storeName}: ${event.target.error.name}`);
                request.onsuccess = (event) => resolve(event.target.result);

            } catch (error) {
                reject(`Error creating transaction on ${storeName}: ${error.message}`);
            }
        });
    }

    // --- Public API ---
    return {
        init, // <--- FIX: This line makes the init function public.

        // --- Project Methods ---
        getProject: (jobNo) => makeRequest(STORES.PROJECTS, 'readonly', 'get', jobNo),
        getAllProjects: () => makeRequest(STORES.PROJECTS, 'readonly', 'getAll'),
        putProject: (projectData) => makeRequest(STORES.PROJECTS, 'readwrite', 'put', projectData),

        // --- Site Data Methods ---
        getSiteData: (jobNo) => makeRequest(STORES.SITE_DATA, 'readonly', 'get', jobNo),
        getAllSiteData: () => makeRequest(STORES.SITE_DATA, 'readonly', 'getAll'),
        putSiteData: (updateData) => makeRequest(STORES.SITE_DATA, 'readwrite', 'put', updateData),

        // --- File Methods ---
        addFile: (fileData) => makeRequest(STORES.FILES, 'readwrite', 'add', fileData),
        deleteFile: (id) => makeRequest(STORES.FILES, 'readwrite', 'delete', null, id),
        getFiles: (jobNo, type) => {
            return new Promise((resolve, reject) => {
                if (!db) return reject("Database not initialized.");
                const store = db.transaction(STORES.FILES).objectStore(STORES.FILES);
                const index = store.index('jobNo_type');
                const request = index.getAll([jobNo, type]);
                request.onsuccess = (e) => resolve(e.target.result || []);
                request.onerror = (e) => reject(e.target.error);
            });
        },

        // --- Helper for creating a new project entry ---
        async createNewProjectEntry(project) {
            const existingSiteData = await this.getSiteData(project.jobNo);
            if (!existingSiteData) {
                console.log(`Creating new site data entry for ${project.jobNo}`);
                // Deep copy the template to avoid mutation issues
                const boqTemplate = JSON.parse(JSON.stringify(FINANCIAL_DATA.boq));
                const newSiteData = {
                    jobNo: project.jobNo,
                    status: 'Pending Start',
                    progress: 0,
                    boq: boqTemplate,
                    mom: [],
                    // Initialize previously certified amounts for payment certs
                    paymentCertificates: []
                };
                await this.putSiteData(newSiteData);
            }
            await this.putProject(project);
        }
    };
})();