
const FINANCIAL_DATA = {
    INITIAL_COSTS: [
        { item: "Trade License G+1 Contracting LLC", amount: 30000 },
        { item: "Local Sponsor Fee (Investor-yearly)", amount: 50000 },
        { item: "Registration & Permits", amount: 50000 },
        { item: "Office Set up", amount: 25000 },
        { item: "Office Rent (3 Months)", amount: 22500 },
        { item: "Office Staff Visas (4 Nos)", amount: 32000 },
        { item: "Workers Visa (12 Nos)", amount: 96000 },
        { item: "Equipment & Tools", amount: 25000 },
        { item: "Vehicles (3 Month Rental) - 3 different vehicles", amount: 19500 },
        { item: "Labor Camp (3 Rooms) - 3 month rent (2.5k each room)", amount: 22500 },
        { item: "Marketing, IT Setup Emails", amount: 15000 },
        { item: "Legal & Miscellaneous Fees", amount: 10000 },
        { item: "Salary of Staff (3 months)", amount: 105000 }
    ],
    YEARLY_OVERHEADS: [
        { item: "Office Rent", amount: 67500 },
        { item: "Office Utilities including mobile sims", amount: 30000 },
        { item: "Office Staff Visas (4 Nos)", amount: 16000 },
        { item: "Office Staff Gratuity+ Ticket yearly (4 Nos)", amount: 8000 },
        { item: "Workers Visa (12 Nos)", amount: 48000 },
        { item: "Vehicles (12 Month Rental) - 3 different vehicles", amount: 58500 },
        { item: "Vehicle Fuel", amount: 18000 },
        { item: "Labor Camp (3 Rooms) - 12 month rent (2.2k each room)", amount: 59400 },
        { item: "Marketing, IT Setup Emails", amount: 5000 },
        { item: "Legal & Miscellaneous Fees", amount: 10000 },
        { item: "Salary of Staff (12 months)", amount: 315000 }
    ],
    FINANCIAL_SUMMARY: [
        { category: "Revenue from 1 Villa Project Approx", amount: 1638248 },
        { category: "Total Revenue from 4 Villa Projects or projects equivalent to 6.5 Million yearly", amount: 6552991 },
        { category: "Overhead Costs yearly (Office Staff, Rent, Miscellaneous)", amount: 635400, isCost: true },
        { category: "Net Profit from each villa approx", amount: 226955, isBold: true },
        { category: "Total Net Profit from 4 Villas", amount: 907820, isBold: true },
        { category: "Gross Profit yearly", amount: 272420, isBold: true },
        { category: "Recovery Cost of investment First Year (80 % Profit Share)", amount: 217936 },
        { category: "Balance Recovery after first year investment", amount: 284564 },
        { category: "Recovery Cost of investment Second Year (80 % Profit Share)", amount: 217936 },
        { category: "Balance Recovery after second year investment", amount: 66629 },
        { category: "Recovery through Monthly Salary to investor for 13 months of AED 5000/-", amount: 65000 }
    ],
    VILLA_BOQ: [
        { id: 1, category: 'Mobilization and Site Setup', item: 'Chairs (For site office)', unit: 'Nos', quantity: 10, rate: 200, total: 2000 },
        { id: 1, category: 'Mobilization and Site Setup', item: 'Tables (For site office)', unit: 'Nos', quantity: 5, rate: 350, total: 1750 },
        { id: 1, category: 'Mobilization and Site Setup', item: 'Air Conditioning (AC) Installation', unit: 'Nos', quantity: 2, rate: 2500, total: 5000 },
        { id: 1, category: 'Mobilization and Site Setup', item: 'Consultant Fees', unit: 'Lump Sum', quantity: 1, rate: 20000, total: 20000, isTotal: true, totalLabel: "Total Mobilization Cost", grandTotal: 62075 },
        { id: 2, category: 'Foundation Excavation Works', item: 'Excavation of Soil (General Excavation for Foundation)', unit: 'Cubic Meter (m³)', quantity: 615, rate: 25, total: 15375 },
        { id: 2, category: 'Foundation Excavation Works', item: 'Machinery Rental (Excavator)', unit: 'Hour (hrs)', quantity: 50, rate: 200, total: 10000 },
        { id: 2, category: 'Foundation Excavation Works', item: 'Labor Costs (Skilled and Unskilled Labor)', unit: 'Labor Day', quantity: 30, rate: 150, total: 4500 },
        { id: 2, category: 'Foundation Excavation Works', item: 'OH & Profit 15%', unit: 'Lump Sum', quantity: 1, rate: 4481, total: 4481, isTotal: true, totalLabel: "Total Foundation Excavation Works", grandTotal: 34356 },
        { id: 3, category: 'Backfill Work (Soil Type A-2-4)', item: 'Backfill Soil (A-2-4 Specification)', unit: 'Cubic Meter (m³)', quantity: 615, rate: 40, total: 24600 },
        { id: 3, category: 'Backfill Work (Soil Type A-2-4)', item: 'OH & Profit 15%', unit: 'Lump Sum', quantity: 1, rate: 3690, total: 3690, isTotal: true, totalLabel: "Total Backfill Work", grandTotal: 28290 },
        { id: 8, category: 'Reinforced Concrete (RC) for Foundations (90 cu.m)', item: 'Timber Shuttering', unit: 'Square Meter (m²)', quantity: 150, rate: 40, total: 6000 },
        { id: 8, category: 'Reinforced Concrete (RC) for Foundations (90 cu.m)', item: 'Reinforcement Steel (Rebar)', unit: 'Ton', quantity: 8, rate: 2400, total: 19200 },
        { id: 8, category: 'Reinforced Concrete (RC) for Foundations (90 cu.m)', item: 'Ready Mix Concrete (90 cu.m)', unit: 'Cubic Meter (m³)', quantity: 90, rate: 270, total: 24300 },
        { id: 8, category: 'Reinforced Concrete (RC) for Foundations (90 cu.m)', item: 'OH & Profit 30%', unit: 'Lump Sum', quantity: 1, rate: 24930, total: 24930, isTotal: true, totalLabel: "Total RC for Foundations", grandTotal: 108030 },
        { id: 31, category: 'Plumbing & Drainage', item: 'Subcontractor rate for 5500 sq.ft villa', unit: 'Lump Sum', quantity: 1, rate: 33000, total: 33000 },
        { id: 31, category: 'Plumbing & Drainage', item: 'OH & Profit 20%', unit: 'Lump Sum', quantity: 1, rate: 4950, total: 4950, isTotal: true, totalLabel: "Total Plumbing", grandTotal: 37950 },
        { id: 37, category: 'Joinery', item: 'Joinery Doors', unit: 'Nos', quantity: 12, rate: 2200, total: 26400 },
        { id: 37, category: 'Joinery', item: 'Kitchen Cabinets', unit: 'Nos', quantity: 1, rate: 25000, total: 25000 },
        { id: 37, category: 'Joinery', item: 'Wardrobes', unit: 'Nos', quantity: 8, rate: 21168, total: 21168 },
        { id: 37, category: 'Joinery', item: 'OH & Profit 15%', unit: 'Lump Sum', quantity: 1, rate: 10885, total: 10885, isTotal: true, totalLabel: "Total Joinery", grandTotal: 83453 },
        { id: 39, category: 'Completion', item: 'Overall Gross Profit (from sheet)', unit: '', quantity: null, rate: null, total: 226955, isTotal: true, totalLabel: "OVERALL GROSS PROFIT", grandTotal: 226955 }
    ],
    
    boq: [
        { id: "1.1", description: "Preliminaries (Mobilization, Fencing, etc.)", unit: "LS", qty: 1, rate: 20000, amount: 20000, prev_perc: 0, curr_perc: 0 },
        { id: "2.2", description: "Back filling", unit: "cu.mt.", qty: 1000, rate: 0.5, amount: 500, prev_perc: 0, curr_perc: 0 },
        { id: "2.3", description: "Disposal", unit: "LS", qty: 1, rate: 8000, amount: 8000, prev_perc: 0, curr_perc: 0 },
        { id: "3.15", description: "Slab on Grade & Basement slab", unit: "M³", qty: 55, rate: 37.51, amount: 2063, prev_perc: 0, curr_perc: 0 },
        { id: "3.16", description: "External Steps", unit: "M²", qty: 18, rate: 70, amount: 1260, prev_perc: 0, curr_perc: 0 },
        { id: "4.7", description: "A/C Foundation, Upstands & Watertanks", unit: "LS", qty: 1, rate: 7000, amount: 7000, prev_perc: 0, curr_perc: 0 },
        { id: "6.2", description: "GRP lining for Water Tanks", unit: "LS", qty: 1, rate: 13000, amount: 13000, prev_perc: 0, curr_perc: 0 },
        { id: "7.2.1", description: "Thermal Insulated Roofing System", unit: "M²", qty: 285, rate: 160, amount: 45600, prev_perc: 0, curr_perc: 0 },
        { id: "7.3.1", description: "Wet Area Waterproofing", unit: "M²", qty: 45, rate: 100, amount: 4500, prev_perc: 0, curr_perc: 0 },
        { id: "10.1", description: "Porcelain Tiles only fixing (3000x1350mm)", unit: "M²", qty: 352, rate: 120, amount: 42240, prev_perc: 0, curr_perc: 0 },
        { id: "10.2", description: "Granite 600x600 (AED 400/m2)", unit: "M²", qty: 30, rate: 520, amount: 15600, prev_perc: 0, curr_perc: 0 },
        { id: "10.3", description: "Unglazed porcelain tiles only fixing", unit: "M²", qty: 47, rate: 60, amount: 2820, prev_perc: 0, curr_perc: 0 },
        { id: "10.4", description: "Parquet flooring only fixing", unit: "M²", qty: 6, rate: 100, amount: 600, prev_perc: 0, curr_perc: 0 },
        { id: "10.5", description: "Ceramic tiles only fixing", unit: "M²", qty: 30, rate: 60, amount: 1800, prev_perc: 0, curr_perc: 0 },
        { id: "10.7", description: "Glazed porcelain (A) only fixing", unit: "M²", qty: 38, rate: 70, amount: 2660, prev_perc: 0, curr_perc: 0 },
        { id: "11.1", description: "Plaster for Internal Walls", unit: "M²", qty: 1765, rate: 14, amount: 24710, prev_perc: 0, curr_perc: 0 },
        { id: "11.2", description: "Ceramic Wall Tiles (300x300mm) only fixing", unit: "M²", qty: 375, rate: 60, amount: 22500, prev_perc: 0, curr_perc: 0 },
        { id: "11.3", description: "Paint for Internal Walls", unit: "M²", qty: 1765, rate: 31.5, amount: 55598, prev_perc: 0, curr_perc: 0 },
        { id: "12.2", description: "Plaster For Elevations", unit: "M²", qty: 1090, rate: 40, amount: 43600, prev_perc: 0, curr_perc: 0 },
        { id: "12.3", description: "Painting for Elevations (Semi Epoxy)", unit: "M²", qty: 1060, rate: 35, amount: 37100, prev_perc: 0, curr_perc: 0 },
        { id: "13.1", description: "Plumbing & Drainage System", unit: "LS", qty: 1, rate: 84000, amount: 84000, prev_perc: 0, curr_perc: 0 },
        { id: "13.3", description: "Electrical work complete", unit: "LS", qty: 1, rate: 99000, amount: 99000, prev_perc: 0, curr_perc: 0 },
        { id: "15.1", description: "Boundary Wall Construction", unit: "RM", qty: 117, rate: 250, amount: 29250, prev_perc: 0, curr_perc: 0 },
        { id: "16A", description: "Builders works, OH & profits", unit: "LS", qty: 1, rate: 40000, amount: 40000, prev_perc: 0, curr_perc: 0 },
        { id: "17.2", description: "Spiral staircase (Provisional)", unit: "PS", qty: 1, rate: 8000, amount: 8000, prev_perc: 0, curr_perc: 0 },
        { id: "17.3", description: "False ceiling work (Provisional)", unit: "PS", qty: 1, rate: 95000, amount: 95000, prev_perc: 0, curr_perc: 0 },
        // ... Other items from the PDF would be added here in the same format
        // This is a representative sample. The full list from the PDF should be entered.
        // The total contract value in the sample PDF is 807,850. I will add a dummy entry to match it.
        { id: "DUMMY", description: "Other Works (Dummy Value to match total)", unit: "LS", qty: 1, rate: 108849, amount: 108849, prev_perc: 0, curr_perc: 0 },
    ]
};
